server:
  port: 8080

tts:
  filepath: e://audio/
  url-path: http://localhost:${server.port}/audio
  audio-access-path: /audio/**
  retention-days: 7

#spring
spring:
  application:
    name: jacob-tts-portal
  profiles:
    active: dev
